# Generated by Django 5.0.4 on 2024-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnlistmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('ssn', models.CharField(max_length=11, verbose_name='Social Security Number')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('education', models.CharField(choices=[('high_school', 'High School Diploma'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate')], max_length=20)),
                ('reasons', models.TextField(verbose_name='Reasons for Enlisting')),
                ('history', models.TextField(blank=True, null=True, verbose_name='Prior Military Service')),
            ],
        ),
    ]
